name: Check Rust

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.10.1
        with:
          cache: false
          components: clippy,rustfmt

      - name: Cache Rust Build
        uses: Swatinem/rust-cache@v2.7.7

      - name: Check Formatting
        run: >
          cargo fmt
          --all
          --check

      - name: Lint with Clippy
        run: >
          cargo clippy
          --all-targets
          --all-features
          --no-deps
          --
          --deny warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.10.1
        with:
          cache: false
          components: rustfmt

      - name: Cache Rust Build
        uses: Swatinem/rust-cache@v2.7.7

      - name: Run Tests
        run: >
          cargo test
          --all-targets
          --all-features
