name: shell-tests

on:
  workflow_call:

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build Executable
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Add target/release to PATH
        run: echo "${{ github.workspace }}/target/${{ matrix.target }}/release" >> $GITHUB_PATH

      - name: Check Symlinks
        run: |
          command_exists() {
            read -r cmd
            command -v "$cmd" >/dev/null 2>&1 || return 1
          }
          ./target/${{ matrix.target }}/release/shell-utils --expand
          ls ./src | grep module_ | ./target/${{ matrix.target }}/release/split 1 -d _ | command_exists
