name: shell-tests

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Executable
        run: |
          cargo build --release

      - name: Update Path
        run: echo "PATH=$GITHUB_WORKSPACE/target/release:$PATH" >> $GITHUB_ENV

      - name: Run Binary
        run: shell-utils --expand
