name: Release

on:
  push:
    tags:
      - "*"
jobs:
  release_assets:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/_release_assets.yaml
